"""Compliance report generator: the artifact a risk committee reads.

Turns the audit trail (and eval-gate evidence) into a model-risk-style
document: what the agent did, which rules fired, who approved what and why,
and proof the record itself is intact.
"""
from __future__ import annotations

from datetime import datetime, timezone

from aegis.audit import AuditLog
from aegis.gates import GateReport


def _fmt_ts(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def generate(audit: AuditLog, gate_reports: list[GateReport] | None = None,
             title: str = "Aegis Compliance Report") -> str:
    entries = audit.entries()
    gate_reports = gate_reports or []

    ok, chain_msg = audit.verify()

    verdicts: dict[str, int] = {}
    policy_hits: dict[str, int] = {}
    approvals: list[dict] = []
    for e in entries:
        v = e.get("policy_verdict") or "n/a"
        verdicts[v] = verdicts.get(v, 0) + 1
        detail = e.get("detail") or {}
        for p in detail.get("policies", []) + detail.get("triggered_policies", []):
            policy_hits[p] = policy_hits.get(p, 0) + 1
        if e.get("action", "").startswith("approval_"):
            approvals.append(e)

    lines = [
        f"# {title}",
        "",
        f"Generated: {_fmt_ts(datetime.now(tz=timezone.utc).timestamp())}",
        f"Audit entries: {len(entries)}",
        f"Chain integrity: {'INTACT' if ok else 'BROKEN'} ({chain_msg})",
        "",
        "## Verdict summary",
        "",
        "| Verdict | Count |",
        "| --- | --- |",
    ]
    for v in sorted(verdicts):
        lines.append(f"| {v} | {verdicts[v]} | ")

    lines += ["", "## Policy triggers", "", "| Policy | Times fired |",
              "| --- | --- |"]
    if policy_hits:
        for p in sorted(policy_hits):
            lines.append(f"| {p} | {policy_hits[p]} |")
    else:
        lines.append("| (none) | 0 |")

    lines += ["", "## Human approvals and overrides", ""]
    if approvals:
        lines += ["| Time | Request | Action | Decision | By | Reason |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for e in approvals:
            d = e.get("detail") or {}
            lines.append(
                f"| {_fmt_ts(e['ts'])} | {d.get('request_id', '')} "
                f"| {d.get('action', '')} | {e['action']} "
                f"| {d.get('decided_by', '')} | {d.get('reason', '')} |"
            )
    else:
        lines.append("No approval decisions recorded in this period.")

    lines += ["", "## Eval gate evidence", ""]
    if gate_reports:
        lines += ["| Suite | Pass rate | Threshold | Verdict | Failures |",
                  "| --- | --- | --- | --- | --- |"]
        for g in gate_reports:
            lines.append(
                f"| {g.suite} | {g.passed}/{g.total} ({g.pass_rate:.1%}) "
                f"| {g.threshold:.0%} | {g.verdict.upper()} "
                f"| {', '.join(g.failures) or 'none'} |"
            )
    else:
        lines.append("No eval gate runs recorded in this period.")

    lines += ["", "---",
              "Generated by Aegis. The hash-chained audit log is the source of truth; "
              "this document is a rendering of it."]
    return "\n".join(lines) + "\n"
